reevoo/reevoo.github.io

docs/reevooapi/customer-experience-review/customer-experience-review-detail.markdown
docs/reevooapi/review/review-detail.markdown

This pull request updates review, review-detail, customer-experience-review-detail pages to include publish_date, purchase_date and delivery_date

[+JL] update review-detail and customer-experience-review-detail

---

css/main.css

Make jobs page responsive

---

_posts/2015-03-17-enjoying-javascript.markdown

Added "Enjoying JavaScript" Article

---

docs/reevooapi/customer-experience-review/customer-experience-review-detail.markdown
docs/reevooapi/review/review-detail.markdown

Update documentation to include fast_response node

---

README.md

How does this look @ZoeFeltham ? :) https://github.com/reevoo/reevoo.github.io/blob/guide/README.md

New post guide

---

css/main.css

Fix mobile layout footer

---

Gemfile
_posts/2015-05-21-your-code-as-a-crime-scene.markdown
css/main.css

Also features some CSS changes to make tables look not crap. :boom:

Your Code as a Crime Scene

---

_layouts/default.html
css/main.css

Fix header title wrapping incorrectly

---

css/main.css

Use dropdown nav earlier to prevent menu displacement

---

css/main.css

Make homepage video responsive

---

_layouts/docs.html
css/main.css

Woop :mobile_phone_off:  :fishing_pole_and_fish:

Responsive docs

---

css/main.css

The mobile nav gets less fugly.

---

_posts/2015-06-15-isolated-javascript.md

Added Isolated Javascript article.

---

.gitignore
Gemfile
Gemfile.lock
README.md
Rakefile.rb
_layouts/post.html
_posts/2014-07-27-ddd-with-ruby.markdown
_posts/2014-07-28-refactoring-without-good-test-coverage.markdown
_posts/2014-07-28-who-does-the-testing.markdown
_posts/2014-07-30-git-bisect-for-great-good.markdown
_posts/2014-07-30-rollback-party.markdown
_posts/2014-08-01-easier-reevoo-assets-integration.markdown
_posts/2014-08-04-stress-driven-development.markdown
_posts/2014-08-08-the-quest-for-our-best-personal-match.markdown
_posts/2014-08-19-shadow-stress-test.markdown
_posts/2014-09-12-http-shooting-party.markdown
_posts/2014-10-27-quality-reviews.markdown
_posts/2014-10-31-helpful-reviews.markdown
_posts/2014-12-01-monday-musings-one.markdown
_posts/2015-03-17-enjoying-javascript.markdown
_posts/2015-05-21-your-code-as-a-crime-scene.markdown
_posts/2015-06-03-20-reevoos-20-percent-time-experiment.markdown
_posts/2015-06-15-isolated-javascript.md
lib/soapbox_comment_linker.rb
soapbox_config.example.yml

This makes reevoo.github.io use Project Soapbox as the comments provider, instead of Disqus.

Soapbox integration

---

_data/jobs.yml

Hide junior and mid-level positions

---

_posts/2015-09-22-how-we-chose-react.md

I'd like some feedback on this, it seems pretty boringly written.

How we chose react

---

_layouts/post.html
soapbox_config.example.yml

@maciekm To merge when Soapbox has been deployed to the new URL.
See also: https://github.com/reevoo/soapbox/pull/76

Upgrade Soapbox production URL

---

README.md
_posts/2015-10-29-upgrading-node.md

This posts tries to explain how to upgrade to Node 4 a project and why the version was bumped from 0.12 to 4.0.

Node upgrade

---

_data/projects.yml
projects/gem-miner/index.markdown
projects/pact-messages/index.markdown
projects/samuel/index.markdown
projects/tabauth/index.markdown

Added tabauth, pact-messages, samuel, and gem-miner

Add latest open source projects

---

_data/projects.yml
projects.html

Updated project page with new and missed-out projects. Also, all descriptions are now full sentences.

Update project page

---

_data/docs.yml
docs/reevooapi/review/downvote-review.markdown
docs/reevooapi/review/review-detail.markdown
docs/reevooapi/review/upvote-review.markdown

This functionality has been merged into the API [here](https://github.com/reevoo/revieworld/pull/1080).

Add documentation for upvoting/downvoting reviews

---

docs/reevooapi/customer-experience-review/customer-experience-review-detail.markdown
docs/reevooapi/customer-experience-review/customer-experience-review-list.markdown

- task: https://reevoo.atlassian.net/browse/PROD-2421
- add nps_score attribute to customer experience review API documentation and also update documentation to the current state of API responses

[+JL] Add nps_scope attribute to customer experience review API documentation

---

about.html

- Removed Richard from team list and added to Alumni's list.
- Removed extra `</a>` closing tag in alumnis.

Move Richard to Alumni's list.

---

_data/docs.yml
css/documentation.css
docs/experiences/experiences-getting-started.markdown
docs/experiences/index.html

[Jira Ticket EX-20](https://reevoo.atlassian.net/browse/EX-20)
This is quite simple, we just needed to add some docs about how to integrate Teasers in client pages. I added some Dion suggestions to make it more understandable. There is also a new set of styles for documentation tables.

Ex 20 add experiences docs

---

css/documentation.css
css/main.css
docs/myreevooapi/fast_response/styles/branding.css

Replaced Lato font with Open Sans to be more consistent with Reevoo design guidelines.

Replaced font

---

_posts/2016-07-28-workshop-first-contact-with-es6-and-react.md

Just a short post to link the ES6 and React workshop.

Added es6 and react workshop video post

---

docs/conversations/conversations-widget-getting-started.markdown

Updating the conversations widget docs to include localisation support

---

docs/conversations/conversations-widget-getting-started.markdown

- task:https://reevoo.atlassian.net/browse/EX-466

Add Norwegian and Portuguese language translation to Ask an owner

---

docs/experiences/experiences-getting-started.markdown

- task: https://reevoo.atlassian.net/browse/EX-529

Add documentation for teasers showTeaserCardsDriver option

---

docs/reevooapi/review/review-detail.markdown
docs/reevooapi/review/review-list.markdown

Include retailer_product information in reviews list endpoint and in the review details endpoint.

Include retailer_product information in reviews endpoint

---

docs/reevooapi/review/review-list.markdown

- ticket: https://reevoo.atlassian.net/browse/EX-924

Add regions documentation to review-list API

---

docs/reevooapi/review-fetcher.markdown
docs/reevooapi/review/review-list.markdown
docs/reevooapi/reviewable/reviewable-detail.markdown
docs/reevooapi/reviewable/reviewable-list.markdown
docs/reevooapi/reviewable/reviewable-short-format-detail.markdown

- Ticket: https://reevoo.atlassian.net/browse/EX-1124
- Removed some old parameters (for automotive)
- Added new parameters (for automotive)
- Added examples of usage
- Modified region parameter description

[EX-1124] Update review-list documentation

---

docs/reevoomark/embedded-product-reviews.markdown
docs/reevoomark/product-badges.markdown

There were two main problems:
- No reference for all the available attributes
- Lack of clarity around hyphen/underscore inconsistency

Improve automotive badge and embedded product review documentation

---

docs/experiences/experiences-getting-started.markdown

- ticket: https://reevoo.atlassian.net/browse/EX-1595
- ticket: https://reevoo.atlassian.net/browse/EX-1520

Add configuration option for cards-per-page and driver-purchase-description

---

docs/reevooapi/review/review-list.markdown

https://reevoo.atlassian.net/browse/PROD-3369
- Update review list doc to dissociate auto and non auto reviews implementation

Update review list doc to dissociate auto and non auto reviews implementation

---

docs/reevoomark/conversation-badges.markdown
docs/reevoomark/customer-experience-badges.markdown
docs/reevoomark/product-badges.markdown

- ticket: https://reevoo.atlassian.net/browse/EX-2321

Add reevoo-click-action and on-click badge configuration to documentation

---

docs/feeds/feeds-automotive-product-fields.markdown

- Add sportswagon as a valid body type in doc

Add sportswagon as valid body type in doc

---

docs/reevooapi/customer-order/customer-order-batch-submission.markdown
docs/reevooapi/customer-order/customer-order-single-submission.markdown

- ticket: https://reevoo.atlassian.net/browse/PROD-3437

Add 403 api response status to customer orders

---

docs/reevooapi/customer-order/customer-order-batch-submission.markdown
docs/reevooapi/customer-order/customer-order-single-submission.markdown

- ticket: https://reevoo.atlassian.net/browse/PROD-3437

Add note about customer order API

---

docs/reevooapi/review/review-detail.markdown

- ticket: https://reevoo.atlassian.net/browse/PROD-3448

Add documentation for came_from_reevoo_launch attribute

---

docs/reevooapi/customer-order/customer-order-batch-submission.markdown
docs/reevooapi/customer-order/customer-order-single-submission.markdown
docs/reevooapi/reviewable/reviewable-short-format-list.markdown
docs/reevoomark/javascript-library.markdown

https://reevoo.atlassian.net/browse/PROD-3463

[PROD-3463] Amend documentation

---

Gemfile.lock
docs/feeds/feeds-automotive-purchaser-fields.markdown
docs/feeds/feeds-dealer-fields.markdown

- move google_place_id documenation from purchaser feed to dealer feed
- also update nokogiry gem which had a vulnerability

move google_place_id documenation from purchaser feed to dealer feed

---

_data/docs.yml
docs/embedded-content/embedded-content.markdown
docs/embedded-content/google-rich-snippets.markdown
docs/embedded-content/index.html
docs/index.markdown

https://reevoo.atlassian.net/browse/PROD-3631

[PROD-3631] Change 'SEO Boost' to 'Embedded Content'

---

docs/reevooapi/conversation/conversation-detail.markdown
docs/reevooapi/conversation/conversation-list.markdown

Related to this previous PR : https://github.com/reevoo/revieworld/pull/1850
This PR update documentation about conversations api which now provides fast_responses field

Update conversations api documentation about new fast_responses field

---

docs/reevoomark/embedded-conversations.markdown
docs/reevoomark/embedded-customer-experience-reviews.markdown
docs/reevoomark/embedded-product-reviews.markdown
docs/reevoomark/embedded-tabbed.markdown

- url update - embedded_reviews.css
Our customers use //mark.reevoo.com/stylesheets/reevoomark/embedded_reviews.css URL which is slower than CDN - //cdn.mark.reevoo.com/assets/embedded_reviews.css

Recommend using cdn.mark.reevoo.com for assets

---

_data/docs.yml
docs/cookie-management/index.html
docs/cookie-management/introduction.markdown

- ticket: https://reevoo.atlassian.net/browse/PLAT-3538

Add cookie management page

---

docs/cookie-management/introduction.markdown
docs/reevoomark/getting-started.markdown
docs/reevoomark/javascript-library.markdown

- chnages an example of including reevoomark javascript file. Defer attribute should make sure, the script is initialized at the moment everything is loaded.

Add documentation for cookie management via script tag attributes
